services:
  postgres:
    image: postgres:15
    container_name: barbershop-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: barbershop
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - barbershop-network

volumes:
  postgres-data:

networks:
  barbershop-network:
    driver: bridge
